<!--
  Main Vue Component, generated by Vue CLI ~gus
-->
<template>
  <div>
    <!--
      Invoke the component using kebab-case
    -->
    <todo-list v-bind:todos="todos"></todo-list>
    <create-todo v-on:create-todo="createTodo"></create-todo>
  </div>
</template>

<script>
/*
  Imports the new TodoList component
*/
import TodoList from './components/TodoList'
import CreateTodo from './components/CreateTodo'

export default {
  name: 'App',
  /*
    Add a reference to the TodoList component. Also add some data functions
  */
  components: {
    TodoList,
    CreateTodo
  },
  data () {
    return {
      todos: [{
        title: 'Example Todo',
        project: 'Example Project',
        done: true
      }]
    }
  },
  methods: {
    createTodo (newTodo) {
      this.todos.push({
        title: newTodo.title,
        project: newTodo.project,
        done: newTodo.done
      })
    }
  }
}
</script>

<style>
</style>
